spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: e84033c9b98706b5ab7c
            clientSecret: 8e550eb028c98040a8be796a7492c135cdaccf8a
          google:
            clientId: 809685880440-4idg7dtjejltuqp6ddtf0mvcrjscnr50.apps.googleusercontent.com
            clientSecret: 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
